import type { TekimaxPlugin, PluginContext, ChatResult, AIActionTag, AIOperation } from '../core/types'

// ─── Operation Keyword Maps ───────────────────────────────────────────────────

/**
 * Keywords matched (case-insensitive) against tool names and response text
 * to infer the CRUD operation. Listed in priority order within each category.
 */
const OPERATION_KEYWORDS: Record<Exclude<AIOperation, 'none'>, ReadonlyArray<string>> = {
    create: [
        'create', 'insert', 'add', 'new', 'generate', 'write', 'make',
        'build', 'compose', 'draft', 'produce', 'post', 'register', 'submit',
    ],
    update: [
        'update', 'edit', 'patch', 'modify', 'change', 'set', 'put',
        'replace', 'rename', 'move', 'reorder', 'revise', 'amend', 'adjust',
    ],
    delete: [
        'delete', 'remove', 'destroy', 'drop', 'clear', 'purge', 'erase',
        'archive', 'cancel', 'deactivate', 'revoke', 'unregister',
    ],
    read: [
        'get', 'fetch', 'list', 'read', 'search', 'find', 'query',
        'retrieve', 'show', 'view', 'load', 'lookup', 'describe', 'inspect',
        'check', 'count', 'summarize', 'explain', 'analyze',
    ],
}

// Pre-build lowercased RegExp per operation for fast matching
const OPERATION_PATTERNS = (Object.entries(OPERATION_KEYWORDS) as Array<[Exclude<AIOperation, 'none'>, ReadonlyArray<string>]>)
    .map(([op, words]) => ({
        op,
        re: new RegExp(`\\b(${words.join('|')})\\b`, 'i'),
    }))

/** Match in priority order: create > delete > update > read */
const MATCH_PRIORITY: Array<Exclude<AIOperation, 'none'>> = ['create', 'delete', 'update', 'read']

function inferFromText(text: string): AIOperation {
    for (const op of MATCH_PRIORITY) {
        const entry = OPERATION_PATTERNS.find(p => p.op === op)
        if (entry?.re.test(text)) return op
    }
    return 'none'
}

/**
 * Infer CRUD operation from a tool function name.
 * Splits on underscores, hyphens, camelCase boundaries then checks keywords.
 * e.g. `createUserRecord` → `create`, `db_delete_row` → `delete`
 */
function inferFromToolName(toolName: string): AIOperation {
    // Normalize camelCase and snake_case into space-separated words
    const normalized = toolName
        .replace(/([a-z])([A-Z])/g, '$1 $2')
        .replace(/[_\-]/g, ' ')
    return inferFromText(normalized)
}

// ─── Plugin Config ─────────────────────────────────────────────────────────────

export interface AIActionTagConfig {
    /**
     * When `true`, also scan the AI's response text for CRUD keywords
     * if no tool calls are present. This is a heuristic and produces
     * `confidence: 'low'` tags. Default: `true`.
     */
    inferFromContent?: boolean

    /**
     * Optional callback invoked after a tag is resolved.
     * Use this to persist tags to your database, analytics, or audit log.
     *
     * @example
     * ```ts
     * new AIActionTagPlugin({
     *   onTag: (tag) => db.auditLog.insert({ ...tag, userId: session.userId }),
     * })
     * ```
     */
    onTag?: (tag: AIActionTag) => void | Promise<void>
}

// ─── Plugin ───────────────────────────────────────────────────────────────────

/**
 * AIActionTagPlugin
 *
 * Attaches an `AIActionTag` to every `ChatResult` and `GenerateTextResult`
 * so your application can:
 * - Display AI-assisted content badges ("Generated by AI")
 * - Track which CRUD operation the AI performed
 * - Feed an audit log for governance / compliance
 *
 * Operation inference priority:
 * 1. Tool call name (high confidence) — `createUser`, `db_delete_row`, etc.
 * 2. Response text keywords (low confidence) — "I've created a new record…"
 * 3. No match → `operation: 'none'`, `confidence: 'none'`
 *
 * @example
 * ```ts
 * import { Tekimax, AIActionTagPlugin } from 'tekimax-omat'
 *
 * const ai = new Tekimax({ provider: openai, plugins: [new AIActionTagPlugin()] })
 * const result = await ai.text.generate({ model: 'gpt-4o', messages })
 *
 * console.log(result.aiTag)
 * // { source: 'ai', operation: 'create', confidence: 'high',
 * //   model: 'gpt-4o', timestamp: 1710374400000, toolName: 'createDocument' }
 * ```
 */
export class AIActionTagPlugin implements TekimaxPlugin {
    name = 'AIActionTagPlugin'

    private cfg: Required<AIActionTagConfig>

    constructor(config: AIActionTagConfig = {}) {
        this.cfg = {
            inferFromContent: config.inferFromContent ?? true,
            onTag: config.onTag ?? (() => {}),
        }
    }

    async afterResponse(context: PluginContext, result: ChatResult): Promise<void> {
        const tag = this.resolve(context.model, result)
        result.aiTag = tag

        try {
            const cb = this.cfg.onTag(tag)
            if (cb instanceof Promise) await cb
        } catch {
            // Never fail a request because of a tag callback
        }
    }

    private resolve(model: string, result: ChatResult): AIActionTag {
        const base: Omit<AIActionTag, 'operation' | 'confidence' | 'toolName'> = {
            source: 'ai',
            model,
            timestamp: Date.now(),
        }

        // --- High confidence: infer from tool call names ---
        const toolCalls = result.message.toolCalls
        if (toolCalls && toolCalls.length > 0) {
            // Use the first tool call (primary action)
            const toolName = toolCalls[0]!.function.name
            const operation = inferFromToolName(toolName)

            if (operation !== 'none') {
                return { ...base, operation, confidence: 'high', toolName }
            }
            // Tool call present but name unrecognized — still tag as AI, operation unknown
            return { ...base, operation: 'none', confidence: 'none', toolName }
        }

        // --- Low confidence: infer from response text ---
        if (this.cfg.inferFromContent) {
            const text = typeof result.message.content === 'string'
                ? result.message.content
                : Array.isArray(result.message.content)
                    ? result.message.content
                        .filter(p => p.type === 'text')
                        .map(p => (p as { type: 'text'; text: string }).text)
                        .join(' ')
                    : ''

            if (text) {
                const operation = inferFromText(text)
                if (operation !== 'none') {
                    return { ...base, operation, confidence: 'low' }
                }
            }
        }

        return { ...base, operation: 'none', confidence: 'none' }
    }
}
